# Generated by Django 5.1.6 on 2025-03-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
