# Generated by Django 5.1.6 on 2025-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircargo', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('carrier_name', models.CharField(max_length=255)),
                ('departure_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_delivery', models.DateField()),
                ('status', models.CharField(choices=[('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('transport_mode', models.CharField(choices=[('Ship', 'Ship'), ('Airplane', 'Airplane')], default='Ship', max_length=10)),
            ],
        ),
    ]
