# Generated by Django 5.1.6 on 2025-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircargo', '0004_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='transport_mode',
            field=models.CharField(choices=[('Ship', 'Usafiri wa Baharini'), ('Airplane', 'Usafiri wa Angani'), ('Road', 'Usafiri wa Barabarani')], default='Ship', max_length=10),
        ),
    ]
